FROM ubuntu:latest AS build

RUN apt-get update
RUN apt-get install openjdk-22-jdk -y
COPY . .

RUN ./mvnw clean package -DskipTests

FROM openjdk:22-jdk-slim

EXPOSE 8080

ENTRYPOINT ["java","-jar","target/umich_nfl-0.0.1-SNAPSHOT.jar"]